---
title: "Transit Agency Profiles"
date: "[Back to home](index.html)"
output: rmdformats::readthedown
---

```{r setup, include=FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE)

```

The Northern Virginia Transportation Commission (NVTC) is working to create Transit Agency Profiles for our six member jurisdictions. These profiles would summarize important service and ridership data for the region in different ways. We plan to use Microsoft Power BI, but before we can make the final product, we have to do a lot of processing and analysis. 

There are two important types of data that will go into our Power BI project: dimension tables and fact tables. **Dimension tables** are the *things* you model, while **fact tables** store the observations/events for those things in the dim tables. You can read a much more eloquent explanation [here](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema). 

For a bit of organization, the code to create the dimension tables and the fact tables has been split up into different documents. Follow the links below to explore the code: 

- **[Dimension Tables](Profiles_DimTables.html)**
- **[Fact Tables](Profiles_FactTables.html)**
